// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu3D2HCAaNbgTesMN-3pb_0B1MZtMx9NI',
    appId: '1:117176313644:web:0c8aff9233db4f7a52ae89',
    messagingSenderId: '117176313644',
    projectId: 'chatapp-d733e',
    authDomain: 'chatapp-d733e.firebaseapp.com',
    storageBucket: 'chatapp-d733e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4cwEWuQSPGX_fmk8efNOQ-rErkIDOJB4',
    appId: '1:117176313644:android:8da243d9dd8496ec52ae89',
    messagingSenderId: '117176313644',
    projectId: 'chatapp-d733e',
    storageBucket: 'chatapp-d733e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHpHziUVovsbJWzaeHPLJukU16nr9Al2w',
    appId: '1:117176313644:ios:6843dc2d6006f94a52ae89',
    messagingSenderId: '117176313644',
    projectId: 'chatapp-d733e',
    storageBucket: 'chatapp-d733e.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHpHziUVovsbJWzaeHPLJukU16nr9Al2w',
    appId: '1:117176313644:ios:a32171e7ec048b6c52ae89',
    messagingSenderId: '117176313644',
    projectId: 'chatapp-d733e',
    storageBucket: 'chatapp-d733e.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
